id: I9F4F98F6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T23:19:48+00:00'
last_modified: '2022-06-08T03:27:25.835984+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22186
  title: བོད་ཀྱི་ཞོ་སྟོན་དུས་ཆེན ༡༩༩༦
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    0CCC:
      image_group_id: I1KG22228
      title: ''
      total_pages: 86
      order: 1
      base_file: 0CCC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
